spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/shopping_list?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '0887149505Yoan!'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
server:
  servlet:
    session:
      timeout: 30m